import type { A2TrackDefinition } from "@/lib/pedagogy/audio/a2/types";

/**
 * Début A2 (8 pistes) — débit clair (150 mots/min), documents courts,
 * vocabulaire connu, informations explicites, 1 à 2 locuteurs.
 */
export const A2_TRACKS_DEBUT: A2TrackDefinition[] = [
  {
    id: "a2-quotidien-routine-matin",
    theme: "vie_quotidienne",
    docType: "dialogue",
    stage: "a2-debut",
    objectif: "Comprendre les horaires et habitudes quotidiennes de deux personnes qui se croisent le matin.",
    pace: "Calme, conversationnel, aucune hésitation.",
    rateWpm: 150,
    gapSeconds: 0.6,
    turns: [
      { voiceId: "voix-b", speakerRole: "Léa", text: "Salut Nora, tu te lèves tôt aujourd'hui !" },
      { voiceId: "voix-c", speakerRole: "Nora", text: "Oui, je commence le travail à huit heures et demie. Je prends le bus de huit heures." },
      { voiceId: "voix-b", speakerRole: "Léa", text: "Ah oui, c'est vrai. Moi, je travaille à dix heures aujourd'hui, alors je reste encore un peu au lit." },
      { voiceId: "voix-c", speakerRole: "Nora", text: "Tu as de la chance ! Bon, je prends mon petit-déjeuner et je pars. À ce soir !" },
      { voiceId: "voix-b", speakerRole: "Léa", text: "À ce soir, bonne journée !" },
    ],
    exercise: {
      id: "a2-quotidien-routine-matin",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute le dialogue et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-quotidien-routine-matin-q1",
          prompt: "À quelle heure Nora prend-elle le bus ?",
          choices: [
            { id: "a", text: "Sept heures" },
            { id: "b", text: "Huit heures" },
            { id: "c", text: "Huit heures et demie" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Huit heures", explanation: "Nora dit : « je prends le bus de huit heures », avant de commencer à huit heures et demie." },
        },
        {
          kind: "vrai_faux",
          id: "a2-quotidien-routine-matin-q2",
          prompt: "Léa travaille avant Nora aujourd'hui.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Léa travaille à dix heures, donc après Nora qui commence à huit heures et demie." },
        },
        {
          kind: "qcm",
          id: "a2-quotidien-routine-matin-q3",
          prompt: "Pourquoi Léa reste-t-elle encore au lit ?",
          choices: [
            { id: "a", text: "Elle est malade" },
            { id: "b", text: "Elle travaille plus tard" },
            { id: "c", text: "Elle ne travaille pas aujourd'hui" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Elle travaille plus tard", explanation: "Elle explique qu'elle travaille à dix heures seulement, donc elle a le temps." },
        },
      ],
    },
  },
  {
    id: "a2-famille-message-presentation",
    theme: "famille",
    docType: "message_vocal",
    stage: "a2-debut",
    objectif: "Repérer des informations pratiques (jour, heure, lieu) et des informations familiales simples dans un message vocal.",
    pace: "Voix posée, ton amical, léger sourire perceptible.",
    rateWpm: 150,
    gapSeconds: 0.5,
    turns: [
      {
        voiceId: "voix-a",
        speakerRole: "Karim",
        text: "Bonjour, c'est Karim, l'étudiant. Je vous laisse ce message parce que j'arrive samedi prochain, vers quinze heures, à la gare. J'ai deux valises, ce n'est pas beaucoup. Ma famille est assez grande : j'ai deux frères et une sœur, mais je voyage seul cette fois. Est-ce que quelqu'un peut venir me chercher à la gare ? Sinon, je peux prendre un taxi, pas de problème. Merci beaucoup, et à samedi !",
      },
    ],
    exercise: {
      id: "a2-famille-message-presentation",
      skillId: "co-annonces-publiques",
      difficulty: "A2",
      instructions: "Écoute le message et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-famille-message-presentation-q1",
          prompt: "Quand est-ce que Karim arrive ?",
          choices: [
            { id: "a", text: "Vendredi" },
            { id: "b", text: "Samedi" },
            { id: "c", text: "Dimanche" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Samedi", explanation: "Karim dit : « j'arrive samedi prochain, vers quinze heures »." },
        },
        {
          kind: "qcm",
          id: "a2-famille-message-presentation-q2",
          prompt: "Combien de frères et sœurs a Karim ?",
          choices: [
            { id: "a", text: "Un frère et une sœur" },
            { id: "b", text: "Deux frères et une sœur" },
            { id: "c", text: "Trois frères" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Deux frères et une sœur", explanation: "Il dit : « j'ai deux frères et une sœur, mais je voyage seul cette fois »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-famille-message-presentation-q3",
          prompt: "Karim demande si quelqu'un peut venir le chercher à la gare.",
          correctAnswer: true,
          correction: { correctAnswer: "Vrai", explanation: "Il demande explicitement si quelqu'un peut venir, tout en précisant qu'il peut aussi prendre un taxi." },
        },
      ],
    },
  },
  {
    id: "a2-achats-boulangerie",
    theme: "achats",
    docType: "dialogue",
    stage: "a2-debut",
    objectif: "Comprendre une transaction simple chez un commerçant : quantités, disponibilité d'un produit, prix.",
    pace: "Rythme d'échange commerçant/cliente, poli et rapide mais clair.",
    rateWpm: 150,
    gapSeconds: 0.5,
    turns: [
      { voiceId: "voix-a", speakerRole: "Boulanger", text: "Bonjour madame, qu'est-ce qu'il vous faut aujourd'hui ?" },
      { voiceId: "voix-b", speakerRole: "Cliente", text: "Bonjour. Je voudrais une baguette pas trop cuite, et deux croissants, s'il vous plaît." },
      { voiceId: "voix-a", speakerRole: "Boulanger", text: "Très bien. Avec ceci ?" },
      { voiceId: "voix-b", speakerRole: "Cliente", text: "Vous avez encore du pain de campagne ?" },
      { voiceId: "voix-a", speakerRole: "Boulanger", text: "Non, désolé, il est déjà tout vendu. Il en reste demain matin." },
      { voiceId: "voix-b", speakerRole: "Cliente", text: "D'accord, tant pis. Ça fait combien ?" },
      { voiceId: "voix-a", speakerRole: "Boulanger", text: "Alors, la baguette, les deux croissants... ça fait quatre euros quarante." },
      { voiceId: "voix-b", speakerRole: "Cliente", text: "Voilà. Merci, au revoir !" },
      { voiceId: "voix-a", speakerRole: "Boulanger", text: "Merci à vous, bonne journée !" },
    ],
    exercise: {
      id: "a2-achats-boulangerie",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute le dialogue et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-achats-boulangerie-q1",
          prompt: "Qu'est-ce que la cliente achète ?",
          choices: [
            { id: "a", text: "Une baguette et deux croissants" },
            { id: "b", text: "Un pain de campagne" },
            { id: "c", text: "Trois croissants" },
          ],
          correctChoiceId: "a",
          correction: { correctAnswer: "Une baguette et deux croissants", explanation: "C'est ce que la cliente commande au début, le pain de campagne n'étant plus disponible." },
        },
        {
          kind: "vrai_faux",
          id: "a2-achats-boulangerie-q2",
          prompt: "Le pain de campagne est disponible aujourd'hui.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Le boulanger répond : « il est déjà tout vendu. Il en reste demain matin »." },
        },
        {
          kind: "qcm",
          id: "a2-achats-boulangerie-q3",
          prompt: "Combien coûtent les achats de la cliente ?",
          choices: [
            { id: "a", text: "4,40 €" },
            { id: "b", text: "4,04 €" },
            { id: "c", text: "14,40 €" },
          ],
          correctChoiceId: "a",
          correction: { correctAnswer: "4,40 €", explanation: "Le boulanger annonce : « ça fait quatre euros quarante »." },
        },
      ],
    },
  },
  {
    id: "a2-transport-annonce-gare-simple",
    theme: "transports",
    docType: "annonce_gare",
    stage: "a2-debut",
    objectif: "Comprendre une annonce de gare courte : destination, heure de départ, voie.",
    pace: "Registre d'annonce publique officielle, débit soutenu mais très intelligible.",
    rateWpm: 150,
    gapSeconds: 0,
    turns: [
      {
        voiceId: "voix-d",
        speakerRole: "Narrateur",
        text: "Attention, votre attention s'il vous plaît. Le train à destination de Lyon, départ dix heures quinze, partira voie B, voie B. Les voyageurs sont priés de se diriger vers la voie B.",
      },
    ],
    exercise: {
      id: "a2-transport-annonce-gare-simple",
      skillId: "co-annonces-publiques",
      difficulty: "A2",
      instructions: "Écoute l'annonce et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-transport-annonce-gare-simple-q1",
          prompt: "Quelle est la destination du train ?",
          choices: [
            { id: "a", text: "Lyon" },
            { id: "b", text: "Paris" },
            { id: "c", text: "Marseille" },
          ],
          correctChoiceId: "a",
          correction: { correctAnswer: "Lyon", explanation: "L'annonce précise : « le train à destination de Lyon »." },
        },
        {
          kind: "qcm",
          id: "a2-transport-annonce-gare-simple-q2",
          prompt: "À quelle heure part le train ?",
          choices: [
            { id: "a", text: "10h50" },
            { id: "b", text: "10h15" },
            { id: "c", text: "15h10" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "10h15", explanation: "L'annonce dit : « départ dix heures quinze »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-transport-annonce-gare-simple-q3",
          prompt: "Le train part de la voie A.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "L'annonce répète deux fois « voie B », pas voie A." },
        },
      ],
    },
  },
  {
    id: "a2-logement-appel-agence",
    theme: "logement",
    docType: "appel_telephonique",
    stage: "a2-debut",
    objectif: "Comprendre les informations pratiques d'une prise de rendez-vous immobilier : disponibilité, étage, horaire choisi.",
    pace: "Professionnel et posé des deux côtés.",
    rateWpm: 150,
    gapSeconds: 0.55,
    turns: [
      { voiceId: "voix-b", speakerRole: "Agence", text: "Agence Immo Centre, bonjour." },
      { voiceId: "voix-a", speakerRole: "Client", text: "Bonjour madame, je vous appelle pour l'appartement de la rue Victor Hugo — il est toujours disponible ?" },
      { voiceId: "voix-b", speakerRole: "Agence", text: "Oui, il est libre. C'est un deux-pièces au troisième étage, sans ascenseur." },
      { voiceId: "voix-a", speakerRole: "Client", text: "D'accord. Est-ce que je pourrais le visiter cette semaine ?" },
      { voiceId: "voix-b", speakerRole: "Agence", text: "Oui, je peux vous proposer jeudi à seize heures, ou vendredi matin." },
      { voiceId: "voix-a", speakerRole: "Client", text: "Jeudi à seize heures, c'est parfait pour moi." },
      { voiceId: "voix-b", speakerRole: "Agence", text: "Très bien, je note votre visite jeudi à seize heures. Votre nom, s'il vous plaît ?" },
      { voiceId: "voix-a", speakerRole: "Client", text: "Diallo, D-I-A-L-L-O." },
      { voiceId: "voix-b", speakerRole: "Agence", text: "Merci monsieur Diallo, à jeudi !" },
    ],
    exercise: {
      id: "a2-logement-appel-agence",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute l'appel téléphonique et réponds aux questions.",
      questions: [
        {
          kind: "vrai_faux",
          id: "a2-logement-appel-agence-q1",
          prompt: "L'appartement a un ascenseur.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "L'agence précise : « au troisième étage, sans ascenseur »." },
        },
        {
          kind: "qcm",
          id: "a2-logement-appel-agence-q2",
          prompt: "Quel jour la visite est-elle finalement fixée ?",
          choices: [
            { id: "a", text: "Mercredi" },
            { id: "b", text: "Jeudi" },
            { id: "c", text: "Vendredi" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Jeudi", explanation: "Le client choisit « jeudi à seize heures », confirmé ensuite par l'agence." },
        },
        {
          kind: "qcm",
          id: "a2-logement-appel-agence-q3",
          prompt: "À quel étage se trouve l'appartement ?",
          choices: [
            { id: "a", text: "Deuxième" },
            { id: "b", text: "Troisième" },
            { id: "c", text: "Quatrième" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Troisième", explanation: "L'agence dit : « un deux-pièces au troisième étage »." },
        },
      ],
    },
  },
  {
    id: "a2-meteo-bulletin-court",
    theme: "meteo",
    docType: "meteo",
    stage: "a2-debut",
    objectif: "Relever des informations météo simples : moment de la journée, température, conditions.",
    pace: "Ton radio enjoué mais posé.",
    rateWpm: 150,
    gapSeconds: 0,
    turns: [
      {
        voiceId: "voix-f",
        speakerRole: "Présentatrice",
        text: "Et voici la météo pour demain. Le matin, il y aura du soleil sur toute la région, avec des températures autour de douze degrés. L'après-midi, quelques nuages arriveront, mais il ne pleuvra pas. Le soir, il fera plus frais, environ six degrés. Bonne journée à tous !",
      },
    ],
    exercise: {
      id: "a2-meteo-bulletin-court",
      skillId: "co-annonces-publiques",
      difficulty: "A2",
      instructions: "Écoute le bulletin météo et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-meteo-bulletin-court-q1",
          prompt: "Quel temps fait-il le matin ?",
          choices: [
            { id: "a", text: "Il pleut" },
            { id: "b", text: "Il y a du soleil" },
            { id: "c", text: "Il neige" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Il y a du soleil", explanation: "Le bulletin annonce : « le matin, il y aura du soleil »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-meteo-bulletin-court-q2",
          prompt: "Il va pleuvoir l'après-midi.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Le bulletin précise : « quelques nuages arriveront, mais il ne pleuvra pas »." },
        },
        {
          kind: "qcm",
          id: "a2-meteo-bulletin-court-q3",
          prompt: "Quelle température fait-il le soir ?",
          choices: [
            { id: "a", text: "12°" },
            { id: "b", text: "6°" },
            { id: "c", text: "20°" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "6°", explanation: "Le bulletin dit : « le soir, il fera plus frais, environ six degrés »." },
        },
      ],
    },
  },
  {
    id: "a2-rdv-medecin-secretariat",
    theme: "rendez_vous",
    docType: "appel_telephonique",
    stage: "a2-debut",
    objectif: "Comprendre une prise de rendez-vous avec reformulation d'horaire : première proposition refusée, horaire final retenu.",
    pace: "Ton cabinet médical, efficace et poli.",
    rateWpm: 150,
    gapSeconds: 0.55,
    turns: [
      { voiceId: "voix-c", speakerRole: "Secrétariat", text: "Cabinet du docteur Bernard, bonjour." },
      { voiceId: "voix-a", speakerRole: "Patient", text: "Bonjour, je voudrais un rendez-vous, s'il vous plaît : j'ai mal à la gorge depuis trois jours." },
      { voiceId: "voix-c", speakerRole: "Secrétariat", text: "D'accord. Alors, le docteur a une place demain à onze heures trente, ça vous convient ?" },
      { voiceId: "voix-a", speakerRole: "Patient", text: "Demain matin, c'est un peu compliqué pour moi, je travaille... Vous n'auriez rien l'après-midi ?" },
      { voiceId: "voix-c", speakerRole: "Secrétariat", text: "Si, j'ai quatorze heures, ou dix-sept heures quinze." },
      { voiceId: "voix-a", speakerRole: "Patient", text: "Dix-sept heures quinze, c'est parfait." },
      { voiceId: "voix-c", speakerRole: "Secrétariat", text: "Parfait. C'est à quel nom ?" },
      { voiceId: "voix-a", speakerRole: "Patient", text: "Mercier, Antoine Mercier." },
      { voiceId: "voix-c", speakerRole: "Secrétariat", text: "Très bien monsieur Mercier, à demain, dix-sept heures quinze !" },
    ],
    exercise: {
      id: "a2-rdv-medecin-secretariat",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute l'appel téléphonique et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-rdv-medecin-secretariat-q1",
          prompt: "Pourquoi le patient veut-il un rendez-vous ?",
          choices: [
            { id: "a", text: "Il a mal au dos" },
            { id: "b", text: "Il a mal à la gorge" },
            { id: "c", text: "Il a mal au ventre" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Il a mal à la gorge", explanation: "Le patient dit : « j'ai mal à la gorge depuis trois jours »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-rdv-medecin-secretariat-q2",
          prompt: "Le patient prend le rendez-vous de onze heures trente proposé au début.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Il refuse ce créneau du matin car il travaille, et demande un rendez-vous l'après-midi." },
        },
        {
          kind: "qcm",
          id: "a2-rdv-medecin-secretariat-q3",
          prompt: "Quel est l'horaire final du rendez-vous ?",
          choices: [
            { id: "a", text: "14h00" },
            { id: "b", text: "17h15" },
            { id: "c", text: "11h30" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "17h15", explanation: "Le patient choisit « dix-sept heures quinze », confirmé par le secrétariat." },
        },
      ],
    },
  },
  {
    id: "a2-loisirs-invitation-vocale",
    theme: "loisirs",
    docType: "message_vocal",
    stage: "a2-debut",
    objectif: "Comprendre une invitation informelle : activité, jour, horaire, lieu de rendez-vous.",
    pace: "Enjoué, familier entre amies.",
    rateWpm: 150,
    gapSeconds: 0,
    turns: [
      {
        voiceId: "voix-c",
        speakerRole: "Camille",
        text: "Salut, c'est Camille ! Dis, ça te dit d'aller au cinéma vendredi soir ? Il y a un nouveau film qui commence à vingt heures. On peut se retrouver devant le cinéma à dix-neuf heures quarante-cinq. Réponds-moi vite si tu es libre. À bientôt !",
      },
    ],
    exercise: {
      id: "a2-loisirs-invitation-vocale",
      skillId: "co-annonces-publiques",
      difficulty: "A2",
      instructions: "Écoute le message et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-loisirs-invitation-vocale-q1",
          prompt: "Quelle activité Camille propose-t-elle ?",
          choices: [
            { id: "a", text: "Un restaurant" },
            { id: "b", text: "Un cinéma" },
            { id: "c", text: "Une piscine" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Un cinéma", explanation: "Elle propose : « ça te dit d'aller au cinéma vendredi soir ? »." },
        },
        {
          kind: "qcm",
          id: "a2-loisirs-invitation-vocale-q2",
          prompt: "À quelle heure commence le film ?",
          choices: [
            { id: "a", text: "19h45" },
            { id: "b", text: "20h00" },
            { id: "c", text: "20h45" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "20h00", explanation: "Camille dit : « il y a un nouveau film qui commence à vingt heures »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-loisirs-invitation-vocale-q3",
          prompt: "Camille propose de se retrouver après le film.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Le rendez-vous (19h45) est avant le début du film (20h00), pas après." },
        },
      ],
    },
  },
  {
    // Ajoutée par le chantier `audio-humanisation` pour corriger le
    // mismatch documenté dans docs/audio/humanisation-a1-a2-b1.md §6.6 :
    // aucune piste A2 existante ne couvrait "se repérer en ville /
    // services publics", le module `a2-se-reperer-en-ville`
    // (lib/pedagogy/data/modules-a2-part1.ts, exercice `ville-o`)
    // utilisait donc par défaut une annonce de gare sans rapport. Cette
    // piste correspond exactement à la `situation` déjà décrite par ce
    // module ("Youssef... demande son chemin... pour aller à la poste,
    // puis se rend à la banque").
    id: "a2-directions-poste-banque",
    theme: "vie_quotidienne",
    docType: "dialogue",
    stage: "a2-debut",
    objectif: "Comprendre des indications pour se repérer en ville (impératif) et un pronom de reprise (COD).",
    pace: "Ton posé, passante serviable et claire.",
    rateWpm: 150,
    gapSeconds: 0.55,
    turns: [
      { voiceId: "voix-a", speakerRole: "Youssef", text: "Excusez-moi, je cherche la poste, elle est loin d'ici ?" },
      { voiceId: "voix-b", speakerRole: "Passante", text: "Non, pas très loin ! Continuez tout droit, puis tournez à gauche au carrefour." },
      { voiceId: "voix-a", speakerRole: "Youssef", text: "D'accord, tout droit, puis à gauche..." },
      { voiceId: "voix-b", speakerRole: "Passante", text: "C'est ça. La poste est juste au coin de la rue, à côté de la pharmacie." },
      { voiceId: "voix-a", speakerRole: "Youssef", text: "Merci beaucoup ! Et la banque, vous savez où elle est aussi ?" },
      { voiceId: "voix-b", speakerRole: "Passante", text: "La banque ? Oui, je la connais bien : c'est juste en face de la poste, vous ne pouvez pas la manquer." },
      { voiceId: "voix-a", speakerRole: "Youssef", text: "Parfait, merci pour ces indications !" },
    ],
    exercise: {
      id: "a2-directions-poste-banque",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute le dialogue et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-directions-poste-banque-q1",
          prompt: "Comment la passante explique-t-elle d'aller à la poste ?",
          choices: [
            { id: "a", text: "Tout droit, puis à gauche" },
            { id: "b", text: "Tout droit, puis à droite" },
            { id: "c", text: "À gauche, puis tout droit" },
          ],
          correctChoiceId: "a",
          correction: { correctAnswer: "Tout droit, puis à gauche", explanation: "Elle dit : « Continuez tout droit, puis tournez à gauche au carrefour »." },
        },
        {
          kind: "qcm",
          id: "a2-directions-poste-banque-q2",
          prompt: "Où se trouve exactement la poste ?",
          choices: [
            { id: "a", text: "Au coin de la rue, à côté de la pharmacie" },
            { id: "b", text: "En face de la mairie" },
            { id: "c", text: "Devant la banque" },
          ],
          correctChoiceId: "a",
          correction: { correctAnswer: "Au coin de la rue, à côté de la pharmacie", explanation: "La passante précise : « La poste est juste au coin de la rue, à côté de la pharmacie »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-directions-poste-banque-q3",
          prompt: "La banque est loin de la poste.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "La passante dit que la banque est « juste en face de la poste »." },
        },
      ],
    },
  },
];
