import type { A2TrackDefinition } from "@/lib/pedagogy/audio/a2/types";

/**
 * Fin A2 (9 pistes) — débit relativement naturel (180 mots/min), messages
 * plus longs, annonces, conversations, récit court, inférence élémentaire
 * (jamais niveau B1 avancé : la réponse reste déductible d'une information
 * explicite proche, jamais d'une implication complexe).
 */
export const A2_TRACKS_FIN: A2TrackDefinition[] = [
  {
    id: "a2-recit-weekend-entre-amies",
    theme: "recits",
    docType: "recit_weekend",
    stage: "a2-fin",
    objectif: "Suivre un récit chronologique (samedi matin/après-midi, dimanche matin/après-midi) et comparer deux week-ends différents.",
    pace: "Naturel, conversation détendue entre amies.",
    rateWpm: 180,
    gapSeconds: 0.45,
    turns: [
      { voiceId: "voix-b", speakerRole: "Léa", text: "Alors, raconte, comment s'est passé ton week-end ?" },
      { voiceId: "voix-c", speakerRole: "Nora", text: "Très bien, en fait je suis allée à la campagne chez mes parents. Samedi matin, j'ai aidé mon père dans le jardin, et l'après-midi, on a fait une grande balade en forêt avec le chien." },
      { voiceId: "voix-b", speakerRole: "Léa", text: "Ah, ça a l'air sympa, ça. Et dimanche ?" },
      { voiceId: "voix-c", speakerRole: "Nora", text: "Alors dimanche, il a plu toute la matinée, du coup on est restés à la maison, on a joué aux cartes, regardé un film... Puis l'après-midi, le soleil est revenu, alors on est sortis manger une glace au village." },
      { voiceId: "voix-b", speakerRole: "Léa", text: "Super ! Moi, euh, j'ai eu un week-end beaucoup plus calme : samedi j'ai fait le ménage et les courses, et dimanche je suis restée chez moi à lire toute la journée. J'avais vraiment besoin de me reposer, en fait." },
      { voiceId: "voix-c", speakerRole: "Nora", text: "Ça fait aussi du bien, de temps en temps ! Bon, on se voit cette semaine ?" },
      { voiceId: "voix-b", speakerRole: "Léa", text: "Oui, avec plaisir, on s'appelle." },
    ],
    exercise: {
      id: "a2-recit-weekend-entre-amies",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute la conversation et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-recit-weekend-entre-amies-q1",
          prompt: "Qu'a fait Nora samedi après-midi ?",
          choices: [
            { id: "a", text: "Du jardinage" },
            { id: "b", text: "Une balade en forêt" },
            { id: "c", text: "Du ménage" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Une balade en forêt", explanation: "Le matin elle a jardiné, « et l'après-midi, on a fait une grande balade en forêt »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-recit-weekend-entre-amies-q2",
          prompt: "Il a plu toute la journée de dimanche chez Nora.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Il a plu seulement le matin ; l'après-midi, « le soleil est revenu »." },
        },
        {
          kind: "qcm",
          id: "a2-recit-weekend-entre-amies-q3",
          prompt: "Comment Léa a-t-elle passé son week-end ?",
          choices: [
            { id: "a", text: "En voyage" },
            { id: "b", text: "Très occupée avec des amis" },
            { id: "c", text: "Calme, à la maison" },
          ],
          correctChoiceId: "c",
          correction: { correctAnswer: "Calme, à la maison", explanation: "Elle décrit un week-end « beaucoup plus calme » entre ménage, courses et lecture." },
        },
      ],
    },
  },
  {
    id: "a2-programme-radio-culturel",
    theme: "evenements",
    docType: "programme",
    stage: "a2-fin",
    objectif: "Repérer plusieurs événements dans une annonce plus longue : jour, lieu, condition/alternative.",
    pace: "Ton animateur radio, enthousiaste et clair, débit un peu plus soutenu.",
    rateWpm: 180,
    gapSeconds: 0,
    turns: [
      {
        voiceId: "voix-d",
        speakerRole: "Animateur",
        text: "Passons maintenant au programme culturel de la semaine. Mercredi, ne manquez pas le marché aux fleurs sur la place centrale, toute la journée. Vendredi soir, un concert gratuit de musique jazz aura lieu au parc municipal, à partir de vingt heures ; en cas de pluie, il sera déplacé à la salle des fêtes. Enfin, samedi et dimanche, le musée d'histoire ouvre gratuitement ses portes à tous les visiteurs, à l'occasion de son trentième anniversaire. Voilà pour cette semaine, je vous souhaite un excellent programme !",
      },
    ],
    exercise: {
      id: "a2-programme-radio-culturel",
      skillId: "co-annonces-publiques",
      difficulty: "A2",
      instructions: "Écoute le programme et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-programme-radio-culturel-q1",
          prompt: "Où a lieu le concert de jazz ?",
          choices: [
            { id: "a", text: "À la salle des fêtes" },
            { id: "b", text: "Au parc municipal" },
            { id: "c", text: "Au musée" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Au parc municipal", explanation: "Le concert « aura lieu au parc municipal », la salle des fêtes n'étant qu'une solution de repli." },
        },
        {
          kind: "vrai_faux",
          id: "a2-programme-radio-culturel-q2",
          prompt: "En cas de pluie, le concert est annulé.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Il n'est pas annulé mais « déplacé à la salle des fêtes »." },
        },
        {
          kind: "qcm",
          id: "a2-programme-radio-culturel-q3",
          prompt: "Pourquoi le musée est-il gratuit ce week-end ?",
          choices: [
            { id: "a", text: "C'est son anniversaire" },
            { id: "b", text: "Ce sont les vacances" },
            { id: "c", text: "C'est un jour férié" },
          ],
          correctChoiceId: "a",
          correction: { correctAnswer: "C'est son anniversaire", explanation: "L'animateur précise : « à l'occasion de son trentième anniversaire »." },
        },
      ],
    },
  },
  {
    id: "a2-appel-service-client-colis",
    theme: "achats",
    docType: "appel_telephonique",
    stage: "a2-fin",
    objectif: "Comprendre la cause d'un problème et inférer la solution proposée, sans qu'elle soit résumée en une phrase unique.",
    pace: "Professionnel, empathique côté conseiller ; légèrement inquiète côté cliente.",
    rateWpm: 180,
    gapSeconds: 0.45,
    turns: [
      { voiceId: "voix-a", speakerRole: "Conseiller", text: "Service client, bonjour, je vous écoute." },
      { voiceId: "voix-f", speakerRole: "Cliente", text: "Bonjour, j'ai commandé un colis il y a dix jours, et je ne l'ai toujours pas reçu... C'est normal ?" },
      { voiceId: "voix-a", speakerRole: "Conseiller", text: "Je suis désolé pour ça. Vous auriez votre numéro de commande ?" },
      { voiceId: "voix-f", speakerRole: "Cliente", text: "Oui, c'est le quatre, quatre, deux, un, neuf." },
      { voiceId: "voix-a", speakerRole: "Conseiller", text: "Un instant... Alors, je vois que le colis a été envoyé, mais il est bloqué depuis trois jours au centre de tri, à cause d'une adresse incomplète : il manque le numéro d'appartement." },
      { voiceId: "voix-f", speakerRole: "Cliente", text: "Ah, c'est possible, j'ai peut-être oublié de l'indiquer... C'est le douze." },
      { voiceId: "voix-a", speakerRole: "Conseiller", text: "Très bien, je corrige l'adresse tout de suite. Normalement, vous devriez recevoir votre colis d'ici deux ou trois jours." },
      { voiceId: "voix-f", speakerRole: "Cliente", text: "D'accord. Et si je ne le reçois toujours pas la semaine prochaine ?" },
      { voiceId: "voix-a", speakerRole: "Conseiller", text: "Dans ce cas, rappelez-nous avec votre numéro de commande, et on vous enverra un nouveau colis gratuitement." },
    ],
    exercise: {
      id: "a2-appel-service-client-colis",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute l'appel téléphonique et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-appel-service-client-colis-q1",
          prompt: "Pourquoi le colis est-il bloqué ?",
          choices: [
            { id: "a", text: "Il est perdu" },
            { id: "b", text: "L'adresse est incomplète" },
            { id: "c", text: "Le magasin est fermé" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "L'adresse est incomplète", explanation: "Le conseiller explique : « il manque le numéro d'appartement »." },
        },
        {
          kind: "qcm",
          id: "a2-appel-service-client-colis-q2",
          prompt: "Que va probablement faire le conseiller juste après cet appel ?",
          choices: [
            { id: "a", text: "Rembourser la cliente" },
            { id: "b", text: "Corriger l'adresse et renvoyer le colis" },
            { id: "c", text: "Annuler la commande" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Corriger l'adresse et renvoyer le colis", explanation: "Il annonce : « je corrige l'adresse tout de suite », l'envoi n'étant pas annulé mais débloqué." },
        },
        {
          kind: "vrai_faux",
          id: "a2-appel-service-client-colis-q3",
          prompt: "Si le colis n'arrive toujours pas, la cliente devra payer un nouveau colis.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Le conseiller précise qu'un nouveau colis serait envoyé « gratuitement »." },
        },
      ],
    },
  },
  {
    id: "a2-reunion-projet-collegues",
    theme: "projets",
    docType: "conversation_travail",
    stage: "a2-fin",
    objectif: "Suivre une réunion à trois voix, distinguer avancement/retard de chaque personne, et inférer si le projet global est en danger.",
    pace: "Réunion de travail informelle, ton posé du manager.",
    rateWpm: 180,
    gapSeconds: 0.45,
    turns: [
      { voiceId: "voix-d", speakerRole: "Manager", text: "Bon, on fait un petit point sur le projet du nouveau site internet. Où en êtes-vous ?" },
      { voiceId: "voix-b", speakerRole: "Julie", text: "De mon côté, j'ai fini les textes pour la page d'accueil et la page contact. Il me reste encore la page des services, je pense terminer ça vendredi." },
      { voiceId: "voix-a", speakerRole: "Karim", text: "Moi, j'ai un peu de retard sur les photos, le photographe n'est disponible que la semaine prochaine. Par contre, j'ai déjà choisi les couleurs et la mise en page avec le graphiste." },
      { voiceId: "voix-d", speakerRole: "Manager", text: "D'accord. Est-ce que ce retard sur les photos va poser un problème pour le lancement du site ?" },
      { voiceId: "voix-a", speakerRole: "Karim", text: "Non, je ne pense pas, parce qu'on peut mettre des photos temporaires en attendant, et les changer plus tard sans problème." },
      { voiceId: "voix-d", speakerRole: "Manager", text: "Parfait, alors on garde la date de lancement dans trois semaines. Julie, tu peux envoyer tes textes à Karim dès qu'ils sont prêts ?" },
      { voiceId: "voix-b", speakerRole: "Julie", text: "Oui, pas de souci, je les enverrai au fur et à mesure." },
    ],
    exercise: {
      id: "a2-reunion-projet-collegues",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute la réunion et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-reunion-projet-collegues-q1",
          prompt: "Qu'est-ce que Julie doit encore terminer ?",
          choices: [
            { id: "a", text: "Les photos" },
            { id: "b", text: "La page des services" },
            { id: "c", text: "La mise en page" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "La page des services", explanation: "Elle dit : « il me reste encore la page des services »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-reunion-projet-collegues-q2",
          prompt: "Karim est en retard parce qu'il n'a pas encore choisi les couleurs du site.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Son retard concerne les photos ; les couleurs et la mise en page sont déjà faites." },
        },
        {
          kind: "qcm",
          id: "a2-reunion-projet-collegues-q3",
          prompt: "Le lancement du site va-t-il probablement être retardé à cause des photos ?",
          choices: [
            { id: "a", text: "Oui, à cause des photos" },
            { id: "b", text: "Non, ils utiliseront des photos temporaires" },
            { id: "c", text: "Oui, à cause des textes" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Non, ils utiliseront des photos temporaires", explanation: "Karim propose une solution qui évite le retard, et le manager garde la date prévue." },
        },
      ],
    },
  },
  {
    id: "a2-annonce-gare-perturbation",
    theme: "transports",
    docType: "annonce_gare",
    stage: "a2-fin",
    objectif: "Comprendre une annonce de perturbation et inférer les deux solutions possibles offertes au voyageur.",
    pace: "Registre d'annonce officielle, plus longue que le début A2, débit soutenu mais intelligible.",
    rateWpm: 180,
    gapSeconds: 0,
    turns: [
      {
        voiceId: "voix-d",
        speakerRole: "Narrateur",
        text: "Mesdames et messieurs, votre attention s'il vous plaît. En raison d'un problème technique, le train numéro huit mille cinq cent quarante-trois à destination de Nantes, prévu à seize heures vingt, est annulé. Les voyageurs sont invités à se présenter au train suivant, à destination de Nantes également, qui partira à dix-sept heures cinq, voie trois, avec leur billet actuel, sans supplément. Pour les personnes ne pouvant pas attendre, un remboursement est possible au guichet d'information, hall principal. Nous vous prions de nous excuser pour la gêne occasionnée.",
      },
    ],
    exercise: {
      id: "a2-annonce-gare-perturbation",
      skillId: "co-annonces-publiques",
      difficulty: "A2",
      instructions: "Écoute l'annonce et réponds aux questions.",
      questions: [
        {
          kind: "vrai_faux",
          id: "a2-annonce-gare-perturbation-q1",
          prompt: "Le train de seize heures vingt est simplement en retard.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "L'annonce dit qu'il « est annulé », pas seulement retardé." },
        },
        {
          kind: "qcm",
          id: "a2-annonce-gare-perturbation-q2",
          prompt: "Que peuvent faire les voyageurs pressés qui ne veulent pas attendre le train suivant ?",
          choices: [
            { id: "a", text: "Prendre un bus" },
            { id: "b", text: "Se faire rembourser au guichet" },
            { id: "c", text: "Payer un supplément" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Se faire rembourser au guichet", explanation: "L'annonce propose : « un remboursement est possible au guichet d'information »." },
        },
        {
          kind: "qcm",
          id: "a2-annonce-gare-perturbation-q3",
          prompt: "À quelle heure et quelle voie part le train de remplacement ?",
          choices: [
            { id: "a", text: "17h05, voie 3" },
            { id: "b", text: "16h20, voie 8" },
            { id: "c", text: "17h50, voie 3" },
          ],
          correctChoiceId: "a",
          correction: { correctAnswer: "17h05, voie 3", explanation: "L'annonce précise : « partira à dix-sept heures cinq, voie trois »." },
        },
      ],
    },
  },
  {
    id: "a2-invitation-mariage-repondeur",
    theme: "evenements",
    docType: "invitation",
    stage: "a2-fin",
    objectif: "Retenir plusieurs détails pratiques dans un message d'invitation assez long : date, lieux, tenue, délai de réponse.",
    pace: "Enthousiaste, débit naturel d'une amie qui annonce une bonne nouvelle.",
    rateWpm: 180,
    gapSeconds: 0,
    turns: [
      {
        voiceId: "voix-c",
        speakerRole: "Amina",
        text: "Bonjour, c'est Amina ! Je t'appelle pour te dire officiellement que je me marie, et j'aimerais beaucoup que tu viennes ! Ce sera le samedi quatorze juin, à quatorze heures, à la mairie du village, et ensuite la fête continuera le soir dans une salle à la campagne, près de chez mes parents. Il faut prévoir une tenue plutôt habillée, mais pas de robe blanche bien sûr ! Si tu viens avec quelqu'un, dis-le-moi avant la fin du mois, pour que je compte les places pour le repas. Il y aura aussi de la musique et de la danse jusqu'à tard le soir. Rappelle-moi vite pour me confirmer, j'ai hâte de te voir là-bas !",
      },
    ],
    exercise: {
      id: "a2-invitation-mariage-repondeur",
      skillId: "co-annonces-publiques",
      difficulty: "A2",
      instructions: "Écoute le message et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-invitation-mariage-repondeur-q1",
          prompt: "Quelle est la date du mariage ?",
          choices: [
            { id: "a", text: "4 juin" },
            { id: "b", text: "14 juin" },
            { id: "c", text: "40 juin" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "14 juin", explanation: "Amina dit : « ce sera le samedi quatorze juin »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-invitation-mariage-repondeur-q2",
          prompt: "La fête du soir a lieu au même endroit que la cérémonie à la mairie.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "La cérémonie est à la mairie, la fête « dans une salle à la campagne, près de chez mes parents »." },
        },
        {
          kind: "qcm",
          id: "a2-invitation-mariage-repondeur-q3",
          prompt: "Avant quand faut-il répondre si on vient accompagné ?",
          choices: [
            { id: "a", text: "Avant le mariage" },
            { id: "b", text: "Avant la fin du mois" },
            { id: "c", text: "Le jour même" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Avant la fin du mois", explanation: "Amina demande : « dis-le-moi avant la fin du mois »." },
        },
      ],
    },
  },
  {
    id: "a2-medecin-suivi-consultation",
    theme: "sante",
    docType: "medecin_pharmacie",
    stage: "a2-fin",
    objectif: "Suivre une consultation de suivi avec plusieurs recommandations (autorisé/interdit, durée, prochaine étape) et inférer une amélioration générale.",
    pace: "Ton de consultation, posé, bienveillant.",
    rateWpm: 180,
    gapSeconds: 0.45,
    turns: [
      { voiceId: "voix-a", speakerRole: "Médecin", text: "Bonjour madame Lefort ! Alors, comment allez-vous depuis la dernière fois ?" },
      { voiceId: "voix-f", speakerRole: "Patiente", text: "Beaucoup mieux, docteur. Le dos me fait encore un peu mal le matin, mais beaucoup moins qu'avant." },
      { voiceId: "voix-a", speakerRole: "Médecin", text: "Très bien, c'est normal, ça prend du temps... Vous continuez les exercices que je vous avais montrés ?" },
      { voiceId: "voix-f", speakerRole: "Patiente", text: "Oui, tous les jours, sauf le week-end dernier, j'étais en voyage." },
      { voiceId: "voix-a", speakerRole: "Médecin", text: "Ce n'est pas grave, l'important c'est la régularité en général. Je vais vous prescrire encore trois semaines de kinésithérapie, deux séances par semaine. Après ça, normalement, vous n'en aurez plus besoin." },
      { voiceId: "voix-f", speakerRole: "Patiente", text: "D'accord. Et je peux recommencer le sport ? J'aimerais bien reprendre la natation." },
      { voiceId: "voix-a", speakerRole: "Médecin", text: "La natation, oui, c'est même très bon pour le dos. Par contre, évitez encore la course à pied pendant un mois." },
      { voiceId: "voix-f", speakerRole: "Patiente", text: "Très bien, merci docteur !" },
      { voiceId: "voix-a", speakerRole: "Médecin", text: "Je vous revois dans trois semaines pour faire le point. Bonne journée !" },
    ],
    exercise: {
      id: "a2-medecin-suivi-consultation",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute la consultation et réponds aux questions.",
      questions: [
        {
          kind: "vrai_faux",
          id: "a2-medecin-suivi-consultation-q1",
          prompt: "La patiente va moins bien que la dernière fois.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Elle dit aller « beaucoup mieux », avec une douleur « beaucoup moins qu'avant »." },
        },
        {
          kind: "qcm",
          id: "a2-medecin-suivi-consultation-q2",
          prompt: "Quel sport le médecin autorise-t-il tout de suite ?",
          choices: [
            { id: "a", text: "La course à pied" },
            { id: "b", text: "La natation" },
            { id: "c", text: "Le tennis" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "La natation", explanation: "Le médecin répond : « la natation, oui, c'est même très bon pour le dos »." },
        },
        {
          kind: "qcm",
          id: "a2-medecin-suivi-consultation-q3",
          prompt: "Combien de temps encore de kinésithérapie ?",
          choices: [
            { id: "a", text: "1 semaine" },
            { id: "b", text: "3 semaines" },
            { id: "c", text: "3 mois" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "3 semaines", explanation: "Le médecin prescrit « encore trois semaines de kinésithérapie »." },
        },
      ],
    },
  },
  {
    id: "a2-recit-voyage-etranger",
    theme: "recits",
    docType: "recit_weekend",
    stage: "a2-fin",
    objectif: "Suivre un récit chronologique de voyage incluant un imprévu, et inférer l'avis global du narrateur malgré l'incident.",
    pace: "Naturel, ton anecdotique entre collègues, léger amusement sur l'imprévu final.",
    rateWpm: 180,
    gapSeconds: 0.45,
    turns: [
      { voiceId: "voix-e", speakerRole: "Farid", text: "Tu sais que je suis parti une semaine au Portugal le mois dernier ?" },
      { voiceId: "voix-b", speakerRole: "Julie", text: "Non ! Raconte, c'était comment ?" },
      { voiceId: "voix-e", speakerRole: "Farid", text: "Super ! Je suis arrivé à Lisbonne un lundi, et les trois premiers jours, j'ai visité la ville : le centre historique, les tramways jaunes, et j'ai mangé beaucoup de pastéis de nata, ces petits gâteaux typiques." },
      { voiceId: "voix-b", speakerRole: "Julie", text: "Miam ! Et ensuite ?" },
      { voiceId: "voix-e", speakerRole: "Farid", text: "Ensuite, jeudi, j'ai pris le train pour Porto, au nord. Là-bas, j'ai visité les caves à vin, et j'ai découvert que je n'aimais pas trop le porto, en fait !" },
      { voiceId: "voix-b", speakerRole: "Julie", text: "Ha ha ! Et tu es rentré directement de Porto ?" },
      { voiceId: "voix-e", speakerRole: "Farid", text: "Non, le dernier jour, je suis revenu à Lisbonne pour reprendre l'avion. Mais il y a eu un problème : mon vol a été annulé à cause d'une grève, et j'ai dû rester une nuit de plus à l'aéroport !" },
      { voiceId: "voix-b", speakerRole: "Julie", text: "Oh non, quelle histoire ! Mais sinon, tu as adoré le voyage ?" },
      { voiceId: "voix-e", speakerRole: "Farid", text: "Oui, malgré ça, c'était un super voyage, j'y retournerai avec plaisir." },
    ],
    exercise: {
      id: "a2-recit-voyage-etranger",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute le récit et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-recit-voyage-etranger-q1",
          prompt: "Quel jour Farid part-il pour Porto ?",
          choices: [
            { id: "a", text: "Lundi" },
            { id: "b", text: "Jeudi" },
            { id: "c", text: "Dimanche" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Jeudi", explanation: "Il dit : « ensuite, jeudi, j'ai pris le train pour Porto »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-recit-voyage-etranger-q2",
          prompt: "Farid a adoré le porto, le vin de la région.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Il dit avoir découvert « que je n'aimais pas trop le porto »." },
        },
        {
          kind: "qcm",
          id: "a2-recit-voyage-etranger-q3",
          prompt: "Que s'est-il passé le dernier jour du voyage ?",
          choices: [
            { id: "a", text: "Il a raté son train" },
            { id: "b", text: "Son vol a été annulé" },
            { id: "c", text: "Il a perdu ses valises" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Son vol a été annulé", explanation: "Il raconte : « mon vol a été annulé à cause d'une grève »." },
        },
        {
          kind: "qcm",
          id: "a2-recit-voyage-etranger-q4",
          prompt: "Comment Farid juge-t-il son voyage, malgré le problème de vol ?",
          choices: [
            { id: "a", text: "Il l'a détesté" },
            { id: "b", text: "C'était un super voyage" },
            { id: "c", text: "Il ne sait pas encore" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "C'était un super voyage", explanation: "Il conclut : « malgré ça, c'était un super voyage, j'y retournerai avec plaisir » — l'imprévu ne change pas son avis global." },
        },
      ],
    },
  },
  {
    id: "a2-copropriete-reunion-travaux",
    theme: "logement",
    docType: "reunion_copropriete",
    stage: "a2-fin",
    objectif: "Suivre une décision collective avec comparaison de deux options, et inférer le choix final avant qu'il ne soit annoncé explicitement.",
    pace: "Réunion posée, ton pragmatique, léger souci d'argent partagé.",
    rateWpm: 180,
    gapSeconds: 0.45,
    turns: [
      { voiceId: "voix-d", speakerRole: "Syndic", text: "Bonsoir à tous, merci d'être venus. On doit décider aujourd'hui pour les travaux de la toiture, il y a deux fuites depuis l'hiver dernier." },
      { voiceId: "voix-c", speakerRole: "Mme Petit", text: "Oui, c'est urgent, chez moi l'eau arrive presque jusqu'au salon quand il pleut fort." },
      { voiceId: "voix-e", speakerRole: "M. Diallo", text: "D'accord pour l'urgence, mais on a deux devis : celui de douze mille euros et celui de dix-huit mille. Quelle différence entre les deux ?" },
      { voiceId: "voix-d", speakerRole: "Syndic", text: "L'entreprise la moins chère refait seulement les parties abîmées. L'autre refait toute la toiture, avec une garantie de vingt ans." },
      { voiceId: "voix-c", speakerRole: "Mme Petit", text: "Vu le prix, moi je préfère la réparation partielle, on n'a pas besoin de refaire tout le toit maintenant." },
      { voiceId: "voix-e", speakerRole: "M. Diallo", text: "Je suis d'accord, surtout que les charges ont déjà augmenté cette année." },
      { voiceId: "voix-d", speakerRole: "Syndic", text: "Très bien, donc si tout le monde est d'accord, on part sur le devis à douze mille euros, travaux prévus le mois prochain. Je vous enverrai les documents à signer par email cette semaine." },
    ],
    exercise: {
      id: "a2-copropriete-reunion-travaux",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute la réunion et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-copropriete-reunion-travaux-q1",
          prompt: "Pourquoi les copropriétaires se réunissent-ils ?",
          choices: [
            { id: "a", text: "Pour parler du jardin" },
            { id: "b", text: "Pour décider des travaux de toiture" },
            { id: "c", text: "Pour élire un nouveau syndic" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Pour décider des travaux de toiture", explanation: "Le syndic annonce : « on doit décider aujourd'hui pour les travaux de la toiture »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-copropriete-reunion-travaux-q2",
          prompt: "Ils choisissent finalement le devis le plus cher.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Ils retiennent « le devis à douze mille euros », le moins cher des deux." },
        },
        {
          kind: "qcm",
          id: "a2-copropriete-reunion-travaux-q3",
          prompt: "Pourquoi préfèrent-ils l'option la moins chère ?",
          choices: [
            { id: "a", text: "Elle est plus rapide" },
            { id: "b", text: "Les charges ont déjà augmenté" },
            { id: "c", text: "L'autre entreprise n'est pas disponible" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Les charges ont déjà augmenté", explanation: "M. Diallo justifie ce choix car « les charges ont déjà augmenté cette année »." },
        },
      ],
    },
  },
];
