import type { A2TrackDefinition } from "@/lib/pedagogy/audio/a2/types";

/**
 * Milieu A2 (9 pistes) — débit modéré (165 mots/min), plusieurs détails,
 * 2-3 locuteurs, reformulation, distracteurs simples (information initiale
 * corrigée en cours de document).
 */
export const A2_TRACKS_MILIEU: A2TrackDefinition[] = [
  {
    id: "a2-travail-nouveau-collegue",
    theme: "travail",
    docType: "conversation_travail",
    stage: "a2-milieu",
    objectif: "Suivre un changement de planning annoncé oralement (distracteur : information initiale corrigée en cours de dialogue).",
    pace: "Chaleureux, premier jour d'un nouveau dans l'équipe.",
    rateWpm: 165,
    gapSeconds: 0.5,
    turns: [
      { voiceId: "voix-b", speakerRole: "Julie", text: "Bonjour ! Tu dois être Karim, le nouveau ? Moi c'est Julie, je travaille au service commercial." },
      { voiceId: "voix-a", speakerRole: "Karim", text: "Ah oui, bonjour Julie ! Enchanté... C'est mon premier jour, je suis un peu perdu." },
      { voiceId: "voix-b", speakerRole: "Julie", text: "C'est normal, ne t'inquiète pas. Tu commences par le service client, c'est ça ?" },
      { voiceId: "voix-a", speakerRole: "Karim", text: "Oui, c'est ça — enfin, on m'a dit ce matin que je vais plutôt commencer par la logistique, avec monsieur Petit. Le service client, ce sera la semaine prochaine." },
      { voiceId: "voix-b", speakerRole: "Julie", text: "Ah d'accord, ça change un peu alors ! Le bureau de monsieur Petit est au deuxième étage, juste à côté de la salle de pause." },
      { voiceId: "voix-a", speakerRole: "Karim", text: "Super, merci beaucoup ! Et la pause déjeuner, c'est à quelle heure ici ?" },
      { voiceId: "voix-b", speakerRole: "Julie", text: "En général vers midi et demi, mais c'est assez libre. On peut déjeuner ensemble aujourd'hui si tu veux, comme ça je te présente l'équipe." },
      { voiceId: "voix-a", speakerRole: "Karim", text: "Avec plaisir, merci Julie !" },
    ],
    exercise: {
      id: "a2-travail-nouveau-collegue",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute le dialogue et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-travail-nouveau-collegue-q1",
          prompt: "Par quel service Karim commence-t-il finalement ?",
          choices: [
            { id: "a", text: "Le service client" },
            { id: "b", text: "La logistique" },
            { id: "c", text: "Le service commercial" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "La logistique", explanation: "Karim corrige : « on m'a dit ce matin que je vais plutôt commencer par la logistique »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-travail-nouveau-collegue-q2",
          prompt: "Karim connaissait déjà ce changement avant ce matin.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Il précise que l'information lui a été donnée « ce matin », donc au dernier moment." },
        },
        {
          kind: "qcm",
          id: "a2-travail-nouveau-collegue-q3",
          prompt: "Où se trouve le bureau de monsieur Petit ?",
          choices: [
            { id: "a", text: "Au premier étage" },
            { id: "b", text: "Au deuxième étage, à côté de la salle de pause" },
            { id: "c", text: "Au rez-de-chaussée" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Au deuxième étage, à côté de la salle de pause", explanation: "Julie donne cette indication précise à Karim." },
        },
      ],
    },
  },
  {
    id: "a2-restaurant-reservation-telephone",
    theme: "loisirs",
    docType: "restaurant",
    stage: "a2-milieu",
    objectif: "Suivre deux changements successifs (horaire puis nombre de personnes) dans une réservation de restaurant.",
    pace: "Poli et professionnel, léger embarras du serveur pour le refus initial.",
    rateWpm: 165,
    gapSeconds: 0.5,
    turns: [
      { voiceId: "voix-a", speakerRole: "Serveur", text: "Restaurant Le Petit Jardin, bonsoir." },
      { voiceId: "voix-b", speakerRole: "Cliente", text: "Bonsoir, je voudrais réserver une table pour samedi soir, s'il vous plaît." },
      { voiceId: "voix-a", speakerRole: "Serveur", text: "Bien sûr. Pour combien de personnes ?" },
      { voiceId: "voix-b", speakerRole: "Cliente", text: "Pour quatre personnes, vers vingt heures." },
      { voiceId: "voix-a", speakerRole: "Serveur", text: "Alors... samedi vingt heures pour quatre... Ah, je suis désolé, à vingt heures c'est complet. J'ai de la place à vingt heures trente, ou à dix-neuf heures." },
      { voiceId: "voix-b", speakerRole: "Cliente", text: "Vingt heures trente, ça marche très bien pour nous. Et en fait, on sera plutôt cinq, ma sœur vient aussi." },
      { voiceId: "voix-a", speakerRole: "Serveur", text: "Pas de problème, une table de cinq à vingt heures trente samedi. C'est à quel nom ?" },
      { voiceId: "voix-b", speakerRole: "Cliente", text: "Rousseau." },
      { voiceId: "voix-a", speakerRole: "Serveur", text: "Parfait madame Rousseau, à samedi !" },
    ],
    exercise: {
      id: "a2-restaurant-reservation-telephone",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute l'appel téléphonique et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-restaurant-reservation-telephone-q1",
          prompt: "Pourquoi la cliente ne peut-elle pas avoir une table à vingt heures ?",
          choices: [
            { id: "a", text: "Le restaurant est fermé" },
            { id: "b", text: "C'est complet" },
            { id: "c", text: "Il n'y a pas de table pour quatre" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "C'est complet", explanation: "Le serveur répond : « à vingt heures c'est complet »." },
        },
        {
          kind: "qcm",
          id: "a2-restaurant-reservation-telephone-q2",
          prompt: "Finalement, combien de personnes seront à table ?",
          choices: [
            { id: "a", text: "Quatre" },
            { id: "b", text: "Cinq" },
            { id: "c", text: "Trois" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Cinq", explanation: "La cliente ajoute sa sœur : « on sera plutôt cinq »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-restaurant-reservation-telephone-q3",
          prompt: "La réservation est finalement à dix-neuf heures.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "La cliente choisit l'autre créneau proposé, vingt heures trente." },
        },
      ],
    },
  },
  {
    id: "a2-hotel-reservation-dates",
    theme: "voyages",
    docType: "hotel",
    stage: "a2-milieu",
    objectif: "Suivre une modification de dates de séjour (mêmes nombre de nuits, dates décalées) — distracteur sur les dates exactes.",
    pace: "Professionnel, accueillant.",
    rateWpm: 165,
    gapSeconds: 0.5,
    turns: [
      { voiceId: "voix-c", speakerRole: "Réceptionniste", text: "Hôtel des Voyageurs, bonjour !" },
      { voiceId: "voix-e", speakerRole: "Client", text: "Bonjour, je voudrais réserver une chambre du trois au six juillet, s'il vous plaît." },
      { voiceId: "voix-c", speakerRole: "Réceptionniste", text: "Une seconde... du trois au six juillet, donc trois nuits. Pour combien de personnes ?" },
      { voiceId: "voix-e", speakerRole: "Client", text: "Pour deux personnes, un lit double si possible." },
      { voiceId: "voix-c", speakerRole: "Réceptionniste", text: "J'ai une chambre double avec vue sur la cour, ça vous va ?" },
      { voiceId: "voix-e", speakerRole: "Client", text: "Oui, très bien. Ah, en fait, est-ce qu'on pourrait plutôt arriver le quatre et repartir le sept ? Nos horaires de train ont changé." },
      { voiceId: "voix-c", speakerRole: "Réceptionniste", text: "Pas de problème, je change ça : du quatre au sept juillet, toujours trois nuits, chambre double. Le petit-déjeuner est inclus." },
      { voiceId: "voix-e", speakerRole: "Client", text: "Parfait, merci beaucoup !" },
    ],
    exercise: {
      id: "a2-hotel-reservation-dates",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute l'appel téléphonique et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-hotel-reservation-dates-q1",
          prompt: "Quelles sont finalement les dates du séjour ?",
          choices: [
            { id: "a", text: "Du 3 au 6 juillet" },
            { id: "b", text: "Du 4 au 7 juillet" },
            { id: "c", text: "Du 4 au 6 juillet" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Du 4 au 7 juillet", explanation: "Le client change ses dates à cause de ses horaires de train, la réceptionniste confirme « du quatre au sept juillet »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-hotel-reservation-dates-q2",
          prompt: "Le petit-déjeuner est inclus dans la réservation.",
          correctAnswer: true,
          correction: { correctAnswer: "Vrai", explanation: "La réceptionniste précise : « le petit-déjeuner est inclus »." },
        },
        {
          kind: "qcm",
          id: "a2-hotel-reservation-dates-q3",
          prompt: "Combien de nuits le client réserve-t-il ?",
          choices: [
            { id: "a", text: "Deux" },
            { id: "b", text: "Trois" },
            { id: "c", text: "Quatre" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Trois", explanation: "Le changement de dates garde la même durée : « toujours trois nuits »." },
        },
      ],
    },
  },
  {
    id: "a2-pharmacie-conseil",
    theme: "sante",
    docType: "medecin_pharmacie",
    stage: "a2-milieu",
    objectif: "Comprendre des conseils de posologie simples : fréquence de prise, condition, durée limite.",
    pace: "Ton professionnel et rassurant du pharmacien.",
    rateWpm: 165,
    gapSeconds: 0.5,
    turns: [
      { voiceId: "voix-d", speakerRole: "Pharmacien", text: "Bonjour ! Je peux vous aider ?" },
      { voiceId: "voix-f", speakerRole: "Cliente", text: "Bonjour, j'ai mal à la tête depuis ce matin, et un peu de fièvre aussi. Vous pourriez me conseiller quelque chose ?" },
      { voiceId: "voix-d", speakerRole: "Pharmacien", text: "Vous avez de la fièvre, vous savez à combien exactement ?" },
      { voiceId: "voix-f", speakerRole: "Cliente", text: "Trente-huit et demi, à peu près." },
      { voiceId: "voix-d", speakerRole: "Pharmacien", text: "D'accord, ce n'est pas très grave. Je vous propose ce médicament : un comprimé toutes les six heures, avec de l'eau, jamais l'estomac vide." },
      { voiceId: "voix-f", speakerRole: "Cliente", text: "Et je peux le prendre combien de jours ?" },
      { voiceId: "voix-d", speakerRole: "Pharmacien", text: "Pas plus de trois jours. Si la fièvre continue après, allez voir votre médecin." },
      { voiceId: "voix-f", speakerRole: "Cliente", text: "D'accord, merci beaucoup !" },
      { voiceId: "voix-d", speakerRole: "Pharmacien", text: "Je vous en prie, et reposez-vous bien !" },
    ],
    exercise: {
      id: "a2-pharmacie-conseil",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute le dialogue et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-pharmacie-conseil-q1",
          prompt: "Quelle est la fréquence de prise du médicament ?",
          choices: [
            { id: "a", text: "Toutes les 3 heures" },
            { id: "b", text: "Toutes les 6 heures" },
            { id: "c", text: "Une fois par jour" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Toutes les 6 heures", explanation: "Le pharmacien dit : « un comprimé toutes les six heures »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-pharmacie-conseil-q2",
          prompt: "Il faut prendre le médicament l'estomac vide.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Le pharmacien précise : « jamais l'estomac vide »." },
        },
        {
          kind: "qcm",
          id: "a2-pharmacie-conseil-q3",
          prompt: "Pendant combien de jours maximum peut-elle prendre le médicament ?",
          choices: [
            { id: "a", text: "1 jour" },
            { id: "b", text: "3 jours" },
            { id: "c", text: "6 jours" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "3 jours", explanation: "Le pharmacien répond : « pas plus de trois jours »." },
        },
      ],
    },
  },
  {
    id: "a2-repondeur-rdv-annule",
    theme: "messages",
    docType: "repondeur",
    stage: "a2-milieu",
    objectif: "Suivre l'annulation d'un rendez-vous et sa reformulation : nouvelle date proposée, action à faire en cas de refus.",
    pace: "Ton professionnel de secrétariat médical, débit régulier.",
    rateWpm: 165,
    gapSeconds: 0,
    turns: [
      {
        voiceId: "voix-b",
        speakerRole: "Secrétariat",
        text: "Bonjour, c'est le cabinet de kinésithérapie. Je vous appelle pour votre rendez-vous de jeudi dix mars à quinze heures : malheureusement, le kinésithérapeute est absent ce jour-là. Je vous propose donc de venir le lendemain, vendredi onze mars, à la même heure, quinze heures. Si ça ne vous convient pas, rappelez-nous au numéro habituel avant mercredi. Merci et à bientôt.",
      },
    ],
    exercise: {
      id: "a2-repondeur-rdv-annule",
      skillId: "co-annonces-publiques",
      difficulty: "A2",
      instructions: "Écoute le message et réponds aux questions.",
      questions: [
        {
          kind: "vrai_faux",
          id: "a2-repondeur-rdv-annule-q1",
          prompt: "Le rendez-vous du jeudi 10 mars est maintenu.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Le kinésithérapeute est absent ce jour-là, le rendez-vous est donc annulé et déplacé." },
        },
        {
          kind: "qcm",
          id: "a2-repondeur-rdv-annule-q2",
          prompt: "Quelle nouvelle date est proposée ?",
          choices: [
            { id: "a", text: "Jeudi 10 mars" },
            { id: "b", text: "Vendredi 11 mars" },
            { id: "c", text: "Lundi 14 mars" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Vendredi 11 mars", explanation: "Le message propose « le lendemain, vendredi onze mars, à la même heure »." },
        },
        {
          kind: "qcm",
          id: "a2-repondeur-rdv-annule-q3",
          prompt: "Que doit faire la personne si la nouvelle date ne lui convient pas ?",
          choices: [
            { id: "a", text: "Aller directement au cabinet" },
            { id: "b", text: "Rappeler avant mercredi" },
            { id: "c", text: "Ne rien faire" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Rappeler avant mercredi", explanation: "Le message dit : « rappelez-nous au numéro habituel avant mercredi »." },
        },
      ],
    },
  },
  {
    id: "a2-projet-vacances-couple",
    theme: "projets",
    docType: "projet_vacances",
    stage: "a2-milieu",
    objectif: "Suivre une décision commune avec ajustement de durée (distracteur sur la préférence initiale de chacun).",
    pace: "Naturel, ton complice de couple.",
    rateWpm: 165,
    gapSeconds: 0.5,
    turns: [
      { voiceId: "voix-a", speakerRole: "Lui", text: "Alors, pour les vacances d'été, on part à la mer ou à la montagne cette année ?" },
      { voiceId: "voix-b", speakerRole: "Elle", text: "Moi je pensais plutôt à la montagne, on n'y est pas allés depuis longtemps. Mais toi, tu préfères toujours la mer, non ?" },
      { voiceId: "voix-a", speakerRole: "Lui", text: "Oui, mais bon, on peut essayer la montagne. Il y a de bonnes randonnées, et il fait moins chaud en août." },
      { voiceId: "voix-b", speakerRole: "Elle", text: "Exactement ! Et les enfants adoreraient voir des vaches et des chèvres là-bas." },
      { voiceId: "voix-a", speakerRole: "Lui", text: "D'accord, la montagne alors. On part deux semaines, du premier au quinze août ?" },
      { voiceId: "voix-b", speakerRole: "Elle", text: "Plutôt dix jours, je crois, parce que ma sœur vient à la maison la dernière semaine d'août." },
      { voiceId: "voix-a", speakerRole: "Lui", text: "Ah oui, c'est vrai, j'avais oublié. Dix jours, ça marche." },
    ],
    exercise: {
      id: "a2-projet-vacances-couple",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute le dialogue et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-projet-vacances-couple-q1",
          prompt: "Où partiront-ils finalement en vacances ?",
          choices: [
            { id: "a", text: "À la mer" },
            { id: "b", text: "À la montagne" },
            { id: "c", text: "À l'étranger" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "À la montagne", explanation: "Il accepte la proposition d'elle : « d'accord, la montagne alors »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-projet-vacances-couple-q2",
          prompt: "Ils partent deux semaines complètes.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Ils réduisent à dix jours à cause de la visite de la sœur." },
        },
        {
          kind: "qcm",
          id: "a2-projet-vacances-couple-q3",
          prompt: "Pourquoi réduisent-ils la durée du voyage ?",
          choices: [
            { id: "a", text: "Ils manquent d'argent" },
            { id: "b", text: "La sœur vient à la maison" },
            { id: "c", text: "Il fait trop chaud" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "La sœur vient à la maison", explanation: "Elle explique : « ma sœur vient à la maison la dernière semaine d'août »." },
        },
      ],
    },
  },
  {
    id: "a2-evenement-anniversaire-surprise",
    theme: "evenements",
    docType: "dialogue",
    stage: "a2-milieu",
    objectif: "Suivre une organisation à trois voix : répartition des tâches entre plusieurs personnes.",
    pace: "Enjoué, ton de préparation d'une surprise, voix un peu basses (secret).",
    rateWpm: 165,
    gapSeconds: 0.5,
    turns: [
      { voiceId: "voix-b", speakerRole: "Nadia", text: "Allô, c'est Nadia. Je vous appelle pour l'anniversaire surprise de Farid samedi. Vous êtes disponibles tous les deux ?" },
      { voiceId: "voix-e", speakerRole: "Marc", text: "Oui, moi je suis libre. Il faut faire ça où, chez toi ?" },
      { voiceId: "voix-b", speakerRole: "Nadia", text: "Oui, chez moi, vers dix-neuf heures. Farid pense qu'on va juste dîner tranquillement tous les trois." },
      { voiceId: "voix-c", speakerRole: "Sophie", text: "Génial ! Je peux apporter le gâteau, j'en fais un super bon au chocolat." },
      { voiceId: "voix-b", speakerRole: "Nadia", text: "Parfait Sophie ! Marc, tu peux t'occuper des décorations et des boissons ?" },
      { voiceId: "voix-e", speakerRole: "Marc", text: "Pas de souci. Et pour le cadeau, on fait un cadeau commun ou chacun le sien ?" },
      { voiceId: "voix-b", speakerRole: "Nadia", text: "Un cadeau commun, c'est mieux je pense. J'ai vu un beau sac de sport, il en a besoin." },
      { voiceId: "voix-c", speakerRole: "Sophie", text: "Bonne idée. Bon, alors samedi dix-neuf heures chez Nadia, avec le gâteau, les décorations et le sac de sport. On garde le secret !" },
    ],
    exercise: {
      id: "a2-evenement-anniversaire-surprise",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute la conversation et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-evenement-anniversaire-surprise-q1",
          prompt: "Qui apporte le gâteau ?",
          choices: [
            { id: "a", text: "Nadia" },
            { id: "b", text: "Marc" },
            { id: "c", text: "Sophie" },
          ],
          correctChoiceId: "c",
          correction: { correctAnswer: "Sophie", explanation: "Sophie propose : « je peux apporter le gâteau »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-evenement-anniversaire-surprise-q2",
          prompt: "Farid sait qu'une fête surprise est organisée pour lui.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Nadia dit que Farid pense qu'ils vont « juste dîner tranquillement », et ils gardent « le secret »." },
        },
        {
          kind: "qcm",
          id: "a2-evenement-anniversaire-surprise-q3",
          prompt: "Quel cadeau choisissent-ils ?",
          choices: [
            { id: "a", text: "Un livre" },
            { id: "b", text: "Un sac de sport" },
            { id: "c", text: "Une montre" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Un sac de sport", explanation: "Nadia propose « un beau sac de sport, il en a besoin », et Sophie confirme ce choix à la fin." },
        },
      ],
    },
  },
  {
    id: "a2-logement-fuite-eau-plombier",
    theme: "logement",
    docType: "probleme_logement",
    stage: "a2-milieu",
    objectif: "Comprendre l'évaluation d'une urgence, la solution provisoire proposée et le rendez-vous fixé.",
    pace: "Ton pratique et rassurant du côté professionnel, légère inquiétude côté locataire.",
    rateWpm: 165,
    gapSeconds: 0.5,
    turns: [
      { voiceId: "voix-a", speakerRole: "Locataire", text: "Allô, oui, c'est urgent : j'ai une fuite d'eau dans ma cuisine, sous l'évier. Vous pourriez venir aujourd'hui ?" },
      { voiceId: "voix-f", speakerRole: "Plombière", text: "Bonjour. Alors, aujourd'hui c'est compliqué, je suis déjà prise toute la journée... Est-ce que la fuite est grave ? Il y a beaucoup d'eau ?" },
      { voiceId: "voix-a", speakerRole: "Locataire", text: "Non, non, ça coule doucement, j'ai mis une bassine en dessous pour l'instant." },
      { voiceId: "voix-f", speakerRole: "Plombière", text: "D'accord, alors ça peut attendre demain matin, vers neuf heures. Fermez l'arrivée d'eau sous l'évier cette nuit, pour être tranquille." },
      { voiceId: "voix-a", speakerRole: "Locataire", text: "D'accord, je vais faire ça. Et ça va coûter combien, à peu près ?" },
      { voiceId: "voix-f", speakerRole: "Plombière", text: "Difficile à dire avant de voir, mais pour une petite fuite comme ça, comptez entre soixante et cent euros." },
      { voiceId: "voix-a", speakerRole: "Locataire", text: "D'accord, très bien. Alors à demain neuf heures, merci !" },
    ],
    exercise: {
      id: "a2-logement-fuite-eau-plombier",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute l'appel téléphonique et réponds aux questions.",
      questions: [
        {
          kind: "vrai_faux",
          id: "a2-logement-fuite-eau-plombier-q1",
          prompt: "La plombière vient aujourd'hui.",
          correctAnswer: false,
          correction: { correctAnswer: "Faux", explanation: "Elle est prise toute la journée et propose de venir demain matin." },
        },
        {
          kind: "qcm",
          id: "a2-logement-fuite-eau-plombier-q2",
          prompt: "Que doit faire le locataire cette nuit ?",
          choices: [
            { id: "a", text: "Rappeler encore" },
            { id: "b", text: "Fermer l'arrivée d'eau" },
            { id: "c", text: "Vider la bassine" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Fermer l'arrivée d'eau", explanation: "La plombière conseille : « fermez l'arrivée d'eau sous l'évier cette nuit »." },
        },
        {
          kind: "qcm",
          id: "a2-logement-fuite-eau-plombier-q3",
          prompt: "Quel est le prix estimé de la réparation ?",
          choices: [
            { id: "a", text: "Entre 60 et 100 €" },
            { id: "b", text: "Plus de 200 €" },
            { id: "c", text: "Gratuit" },
          ],
          correctChoiceId: "a",
          correction: { correctAnswer: "Entre 60 et 100 €", explanation: "La plombière dit : « comptez entre soixante et cent euros »." },
        },
      ],
    },
  },
  {
    id: "a2-interview-simple-metiers",
    theme: "travail",
    docType: "interview_simple",
    stage: "a2-milieu",
    objectif: "Repérer des métiers et des informations associées chez plusieurs locuteurs brefs (micro-trottoir).",
    pace: "Journalistique, questions courtes et réponses spontanées.",
    rateWpm: 165,
    gapSeconds: 0.5,
    turns: [
      { voiceId: "voix-f", speakerRole: "Journaliste", text: "Bonjour ! Je fais un petit reportage sur les métiers, vous faites quoi dans la vie ?" },
      { voiceId: "voix-d", speakerRole: "Homme interviewé", text: "Moi je suis infirmier, je travaille dans un hôpital, la nuit surtout." },
      { voiceId: "voix-f", speakerRole: "Journaliste", text: "Ah, et vous aimez ça, travailler la nuit ?" },
      { voiceId: "voix-d", speakerRole: "Homme interviewé", text: "Oui, c'est plus calme, et je suis payé un peu plus... Mais c'est fatigant pour la famille." },
      { voiceId: "voix-f", speakerRole: "Journaliste", text: "Merci ! Et vous madame, vous travaillez dans quoi ?" },
      { voiceId: "voix-c", speakerRole: "Femme interviewée", text: "Moi je suis institutrice, je travaille avec des enfants de six ans. J'adore mon métier ! Même si c'est fatigant aussi, mais différemment." },
      { voiceId: "voix-f", speakerRole: "Journaliste", text: "Merci beaucoup à tous les deux !" },
    ],
    exercise: {
      id: "a2-interview-simple-metiers",
      skillId: "co-dialogues-simples",
      difficulty: "A2",
      instructions: "Écoute l'interview et réponds aux questions.",
      questions: [
        {
          kind: "qcm",
          id: "a2-interview-simple-metiers-q1",
          prompt: "Quel est le métier de l'homme interviewé ?",
          choices: [
            { id: "a", text: "Instituteur" },
            { id: "b", text: "Infirmier" },
            { id: "c", text: "Journaliste" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "Infirmier", explanation: "Il répond : « moi je suis infirmier, je travaille dans un hôpital »." },
        },
        {
          kind: "qcm",
          id: "a2-interview-simple-metiers-q2",
          prompt: "Avec quel âge d'enfants travaille la femme interviewée ?",
          choices: [
            { id: "a", text: "3 ans" },
            { id: "b", text: "6 ans" },
            { id: "c", text: "10 ans" },
          ],
          correctChoiceId: "b",
          correction: { correctAnswer: "6 ans", explanation: "Elle précise : « je travaille avec des enfants de six ans »." },
        },
        {
          kind: "vrai_faux",
          id: "a2-interview-simple-metiers-q3",
          prompt: "L'infirmier trouve son travail de nuit difficile pour sa famille.",
          correctAnswer: true,
          correction: { correctAnswer: "Vrai", explanation: "Il dit : « c'est fatigant pour la famille »." },
        },
      ],
    },
  },
];
